import { useEffect, useState, useCallback } from "react";
import { Copy, Check } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog.js";
import { Button } from "@/components/ui/button.js";

interface OnboardingModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const CODE_CLASS = "rounded bg-muted px-1.5 py-0.5 text-xs font-mono";

const SETUP_COMMANDS = [
  "npm i -g amber-cards",
  "amber login",
  "amber install-plugin",
];

function SetUpContent() {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(SETUP_COMMANDS.join(" && "));
    setCopied(true);
  }, []);

  useEffect(() => {
    if (!copied) return;
    const timer = setTimeout(() => setCopied(false), 2000);
    return () => clearTimeout(timer);
  }, [copied]);

  return (
    <div className="space-y-3 text-sm text-muted-foreground">
      <div className="relative rounded-md bg-muted/50 p-3">
        <div className="flex flex-col gap-2 font-mono text-xs">
          {SETUP_COMMANDS.map((cmd) => (
            <span key={cmd}>
              <span className="select-none text-muted-foreground/60">$ </span>
              {cmd}
            </span>
          ))}
        </div>
        <button
          onClick={handleCopy}
          className="absolute top-2 right-2 rounded-md p-1.5 text-muted-foreground/60 hover:text-foreground hover:bg-muted transition-colors"
        >
          {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
        </button>
      </div>
      <p className="text-xs text-muted-foreground/70">
        Tip: use <code className={CODE_CLASS}>amber install-plugin --local</code> to install for a specific repo only.
      </p>
    </div>
  );
}

const STEPS = [
  {
    title: "Welcome to Amber",
    content: (
      <p className="text-sm text-muted-foreground">
        Amber turns your Claude Code sessions into flashcards so you retain what you learn through spaced repetition.
      </p>
    ),
  },
  {
    title: "Set Up",
    content: <SetUpContent />,
  },
  {
    title: "The Loop",
    content: (
      <div className="flex items-start justify-center gap-3 text-sm py-2">
        <div className="flex flex-col items-center gap-1.5 flex-1">
          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-muted text-base">1</div>
          <span className="font-medium text-foreground">Code</span>
          <span className="text-xs text-muted-foreground text-center">Use Claude Code normally</span>
        </div>
        <span className="text-muted-foreground/50 text-lg mt-3">&rarr;</span>
        <div className="flex flex-col items-center gap-1.5 flex-1">
          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-muted text-base">2</div>
          <span className="font-medium text-foreground">Cards appear</span>
          <span className="text-xs text-muted-foreground text-center">Auto-generated by the plugin</span>
        </div>
        <span className="text-muted-foreground/50 text-lg mt-3">&rarr;</span>
        <div className="flex flex-col items-center gap-1.5 flex-1">
          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-muted text-base">3</div>
          <span className="font-medium text-foreground">Review</span>
          <span className="text-xs text-muted-foreground text-center">Come back when due</span>
        </div>
      </div>
    ),
  },
] as const;

export default function OnboardingModal({ open, onOpenChange }: OnboardingModalProps) {
  const [step, setStep] = useState(0);

  // Reset to the first step whenever the modal opens
  useEffect(() => {
    if (open) {
      setStep(0);
    }
  }, [open]);

  const isFirst = step === 0;
  const isLast = step === STEPS.length - 1;

  return (
    <Dialog open={open} onOpenChange={(v) => { if (isLast) onOpenChange(v); }}>
      <DialogContent
        className="sm:max-w-lg"
        showCloseButton={isLast}
        onInteractOutside={(e) => { if (!isLast) e.preventDefault(); }}
        onEscapeKeyDown={(e) => { if (!isLast) e.preventDefault(); }}
      >
        <DialogHeader>
          <DialogTitle>{STEPS[step].title}</DialogTitle>
          <DialogDescription className="sr-only">
            Onboarding step {step + 1} of {STEPS.length}
          </DialogDescription>
        </DialogHeader>

        {STEPS[step].content}

        <DialogFooter className="sm:justify-between">
          {/* Step dot indicators */}
          <div className="flex items-center gap-1.5">
            {STEPS.map((_, i) => (
              <span
                key={i}
                className={`h-1.5 w-1.5 rounded-full transition-colors ${
                  i === step ? "bg-foreground" : "bg-muted-foreground/30"
                }`}
              />
            ))}
          </div>

          {/* Navigation buttons */}
          <div className="flex gap-2">
            {!isFirst && (
              <Button variant="outline" size="sm" onClick={() => setStep(step - 1)}>
                Back
              </Button>
            )}
            {isLast ? (
              <Button size="sm" onClick={() => onOpenChange(false)}>
                Done
              </Button>
            ) : (
              <Button size="sm" onClick={() => setStep(step + 1)}>
                Next
              </Button>
            )}
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
